# Generated by Django 3.2.20 on 2023-10-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('events', models.CharField(max_length=200)),
            ],
        ),
    ]
